import { expect, test } from './fixtures'
import { iso, openSettings, seed, state } from './helpers'

test('first run: name, goal and schedule build a first month, then Home shows today', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('What should we call you?').fill('Jay')
  await page.getByRole('button', { name: 'Kilograms (kg)' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: /Build muscle/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  // Where they train, what they like, and their cardio.
  await expect(page.getByRole('heading', { name: 'Where do you usually train?' })).toBeVisible()
  await page.getByRole('radio', { name: 'CrossFit box' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: /^CrossFit-style/ }).click()
  await page.getByRole('button', { name: /^Heavy strength/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Any exercises you prefer?' })).toBeVisible()
  await page.getByRole('radiogroup', { name: 'Free weights' }).getByRole('radio', { name: 'More' }).click()
  await page.getByRole('radiogroup', { name: 'Machines' }).getByRole('radio', { name: 'Less' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  const cardio = page.getByRole('group', { name: 'Cardio you like' })
  await expect(cardio.getByRole('button', { name: 'Stair climber' })).toBeVisible()
  await cardio.getByRole('button', { name: 'Rower' }).click()
  await cardio.getByRole('button', { name: 'Air bike (Assault / Echo)' }).click()
  await page.getByRole('radio', { name: 'Split the time between them' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: '4', exact: true }).click()
  await page.getByRole('button', { name: 'Build my plan' }).click()
  await expect(page.getByRole('heading', { name: 'Your first week' })).toBeVisible()
  await page.getByRole('button', { name: 'Start my plan' }).click()
  // Set-up done: the app tour starts on Home (it can wait).
  const tour = page.getByRole('dialog', { name: 'App tour' })
  await expect(tour.getByText('Welcome to Durata 👋')).toBeVisible()
  await tour.getByRole('button', { name: 'Not now' }).click()
  await expect(tour).toHaveCount(0)
  await expect(page.getByRole('heading', { name: /, Jay$/ })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Durata' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Today' })).toBeVisible()
  const s = await state(page)
  expect(s.programs).toHaveLength(1)
  expect(Object.keys(s.overrides).length).toBeGreaterThan(20)
  expect(s.units.weight).toBe('kg')
  expect(s.onboarded).toBe(true)
  expect(s.equipment).toEqual(['Barbell', 'Dumbbell', 'Kettlebell', 'Machine', 'Other'])
  expect(s.trainingPrefs).toEqual({ styles: ['crossfit', 'strength'], cardio: ['row', 'airbike'], cardioSplit: true, moves: { free: 1, machine: -1 }, goals: ['muscle'], goal: null })
})

test('first run with no plan still asks where you train and what you like', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: /Just log my workouts/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('radio', { name: 'Bodyweight only' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'No preference, continue' }).click()
  await page.getByRole('button', { name: 'No preference, continue' }).click()
  // Bodyweight only is about lifting gear: a treadmill or bike at home can still be picked.
  const cardio = page.getByRole('group', { name: 'Cardio you like' })
  await expect(cardio.getByRole('button', { name: 'Treadmill', exact: true })).toBeVisible()
  await cardio.getByRole('button', { name: 'Running' }).click()
  await page.getByRole('button', { name: 'Start using the app' }).click()
  await expect(page.getByText('Nothing planned today')).toBeVisible()
  const s = await state(page)
  expect(s.equipment).toEqual([])
  expect(s.trainingPrefs.cardio).toEqual(['run'])
  expect(s.programs ?? []).toHaveLength(0)
})

test('first run can be skipped straight to Home', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Skip' }).click()
  await expect(page.getByText('Nothing planned today')).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'App tour' })).toHaveCount(0)
})

test('Home with nothing planned: repeat the last workout in one tap', async ({ page }) => {
  await seed(page, { logs: [{ exerciseId: 'Pushups', date: '2026-01-05', sets: [{ weight: null, reps: 15 }, { weight: null, reps: 12 }] }] })
  await page.goto('/')
  await page.getByRole('button', { name: /Repeat last workout/ }).click()
  await expect(page.getByRole('button', { name: '✓ Finish workout' })).toBeVisible()
  await expect(page.getByText('Push-Up').first()).toBeVisible()
  const s = await state(page)
  const today = Object.entries(s.overrides as Record<string, { exerciseId: string; sets: number; reps?: number }[]>).find(([, v]) => v.length)
  expect(today?.[1]).toEqual([{ exerciseId: 'Pushups', sets: 2, reps: 15 }])
  expect(s.plan.flat()).toEqual([])
})

test('Pick exercises from Home, then add another mid-workout', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.getByRole('button', { name: /Pick exercises/ }).click()
  await page.getByPlaceholder(/search/i).fill('bench press')
  await page.locator('.fixed button', { hasText: /^Bench Press/ }).first().click()
  await page.locator('.fixed').getByRole('button', { name: 'Done' }).click()
  await expect(page.getByRole('button', { name: 'Bench Press', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '+ Add exercise' }).click()
  await page.getByPlaceholder(/search/i).fill('lat pulldown')
  await page.locator('.fixed button', { hasText: /^Lat Pulldown/ }).first().click()
  await page.locator('.fixed').getByRole('button', { name: 'Done' }).click()
  await expect(page.getByRole('button', { name: 'Lat Pulldown', exact: true })).toBeVisible()
  expect((await state(page)).plan.flat()).toEqual([])
})

test('plan and log an exercise, then see it in History', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.getByText('Add an exercise').click()
  // The library's old name finds the everyday one.
  await page.getByPlaceholder(/search/i).fill('Pushups')
  await page.locator('.fixed button').filter({ has: page.locator('span', { hasText: /^Push-Up$/ }) }).first().click()
  await page.locator('.fixed').getByRole('button', { name: /Done|Close/ }).first().click()
  await page.locator('input[type=number]').first().fill('20')
  await expect.poll(async () => (await state(page)).logs.length).toBe(1)
  await page.locator('nav').getByText('Progress').click()
  await page.getByRole('button', { name: 'Exercises' }).click()
  await expect(page.getByText('Push-Up', { exact: true })).toBeVisible()
})

test('randomizer builds a timed workout with a clock', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.locator('.fixed').getByText('Make me a workout').click()
  await page.locator('.fixed').getByRole('button', { name: 'Conditioning', exact: true }).click()
  await page.locator('.fixed').getByRole('button', { name: 'Timed', exact: true }).click()
  await page.locator('.fixed').getByRole('button', { name: 'EMOM', exact: true }).click()
  await page.locator('.fixed').getByRole('button', { name: /^Generate/ }).click()
  await page.locator('.fixed').getByRole('button', { name: /^Add to/ }).click()
  await expect(page.getByText('Timed workout').first()).toBeVisible()
  await page.getByRole('button', { name: /Start timer/ }).first().click()
  await expect(page.locator('.fixed').getByText(/Interval 1 of/)).toBeVisible()
})

test('damaged saved data does not crash the app', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('workout-app-v1', JSON.stringify({ state: { plan: 'bad', logs: [null, { exerciseId: 1 }], tourDone: true, tourVersion: 1000, socialChoice: 'declined', overrides: 5 }, version: 1 })))
  await page.goto('/')
  await expect(page.getByText('Goals')).toBeVisible()
})

test('randomizer: style groups with variations, and several styles with their own minutes', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.locator('.fixed').getByText('Make me a workout').click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Strength', exact: true }).click()
  // The first tap on a kind picks it; later taps add more.
  await sheet.getByRole('button', { name: 'Conditioning', exact: true }).click()
  await sheet.getByRole('button', { name: 'Lifting', exact: true }).click()
  await sheet.getByRole('button', { name: 'Cardio', exact: true }).click()
  await sheet.getByRole('button', { name: 'HIIT', exact: true }).click()
  await sheet.getByRole('button', { name: 'PHA', exact: true }).click()
  await expect(sheet.getByRole('button', { name: 'HIIT circuit', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await sheet.getByRole('button', { name: 'Chest', exact: true }).click()
  await expect(sheet.getByText('Time for each part')).toBeVisible()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText(/Strength \+ PHA · Chest \+ Cardio/)).toBeVisible()
})

test('randomizer remembers the last choices, and Full body is one tap', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.locator('.fixed').getByText('Make me a workout').click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Full body', exact: true }).click()
  await expect(sheet.getByRole('button', { name: 'Hamstrings', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await sheet.getByRole('button', { name: '30 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await sheet.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.locator('.fixed').getByText('Make me a workout').click()
  await expect(sheet.getByRole('button', { name: 'Full body', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(sheet.getByRole('button', { name: '30 min', exact: true })).toHaveClass(/bg-accent/)
})

test('plan edits change one date; Repeat every weekday makes it the usual week', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Add exercises' }).click()
  await page.getByPlaceholder(/search/i).fill('push-up')
  await page.locator('.fixed button', { hasText: /^Push-Up/ }).first().click()
  await page.locator('.fixed').getByRole('button', { name: /Done|Close/ }).first().click()
  let s = await state(page)
  expect(s.plan.flat()).toEqual([])
  expect(Object.values(s.overrides).flat()).toHaveLength(1)
  await expect(page.getByRole('button', { name: /Chest.*|, Chest/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Day options' }).click()
  await page.getByRole('button', { name: /^Repeat every/ }).click()
  s = await state(page)
  expect(s.plan.flat()).toHaveLength(1)
  expect(Object.keys(s.overrides)).toHaveLength(0)
  await page.getByRole('button', { name: 'Day options' }).click()
  await expect(page.getByRole('button', { name: /^Stop repeating every/ })).toBeVisible()
})

test('a set is one tap: ✓ logs the target, and typed numbers win', async ({ page }) => {
  await seed(page, {
    overrides: { [iso(0)]: [{ exerciseId: 'Barbell_Squat', sets: 2, reps: 5 }] },
    logs: [{ date: iso(-4), exerciseId: 'Barbell_Squat', sets: [{ weight: 185, reps: 5 }, { weight: 185, reps: 5 }] }],
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await expect(page.getByText(/Last time: 185×5 · 185×5/)).toBeVisible()
  await page.getByRole('button', { name: 'Set 1 done' }).click()
  // 2 × 5 last time, the target once: a rep more first (weight goes up once it holds).
  await expect(page.getByRole('spinbutton', { name: 'Set 1 lb' })).toHaveValue('185')
  await expect(page.getByRole('spinbutton', { name: 'Set 1 reps' })).toHaveValue('6')
  await page.getByRole('spinbutton', { name: 'Set 2 lb' }).fill('190')
  await page.getByRole('button', { name: 'Set 2 done' }).click()
  // Every set ticked: the card folds to one line with what was done; tap to open it again.
  await expect(page.getByRole('button', { name: /2 of 2 sets · 185×6 · 190×6/ })).toBeVisible()
  await expect(page.getByRole('spinbutton', { name: 'Set 2 lb' })).toHaveCount(0)
  await page.getByRole('button', { name: /2 of 2 sets/ }).click()
  await expect(page.getByRole('spinbutton', { name: 'Set 2 lb' })).toHaveValue('190')
  await expect.poll(async () => (await state(page)).logs.find((l: { date: string }) => l.date === iso(0))?.sets).toEqual([
    { weight: 185, reps: 6, seconds: null, done: true, auto: true },
    { weight: 190, reps: 6, seconds: null, done: true, auto: false },
  ])

  // A tap by mistake comes off again: an auto-filled set empties, a typed one keeps its numbers.
  await page.getByRole('button', { name: 'Set 1 done' }).click()
  await expect(page.getByRole('button', { name: 'Set 1 done' })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('spinbutton', { name: 'Set 1 lb' })).toHaveValue('')
  await page.getByRole('button', { name: 'Set 2 done' }).click()
  await expect(page.getByRole('button', { name: 'Set 2 done' })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('spinbutton', { name: 'Set 2 lb' })).toHaveValue('190')
})

test('a set menu: make it a warm-up or delete that one set; future days show the plan without ticks', async ({ page }) => {
  await seed(page, { overrides: { [iso(0)]: [{ exerciseId: 'Pushups', sets: 3, reps: 10 }], [iso(1)]: [{ exerciseId: 'Pushups', sets: 3, reps: 10 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await page.getByRole('spinbutton', { name: 'Set 1 reps' }).fill('11')
  await page.getByRole('spinbutton', { name: 'Set 2 reps' }).fill('12')
  await page.getByRole('spinbutton', { name: 'Set 3 reps' }).fill('13')
  await page.getByRole('button', { name: 'Set 2 options' }).click()
  await page.getByRole('button', { name: 'Delete this set' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Set 2 reps' })).toHaveValue('13')
  await expect(page.getByRole('spinbutton', { name: 'Set 3 reps' })).toHaveCount(0)
  const s = await state(page)
  expect(s.overrides[iso(0)][0].sets).toBe(2)
  expect(s.logs.find((l: { date: string }) => l.date === iso(0)).sets.map((x: { reps: number }) => x.reps)).toEqual([11, 13])

  // Tomorrow: the plan is there, but nothing to tick yet.
  const t = new Date()
  t.setDate(t.getDate() + 1)
  if (t.getDay() === 1) await page.getByRole('button', { name: 'Next week' }).click()
  await page.getByRole('button', { name: new RegExp(`^${t.toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })}`) }).click()
  await expect(page.getByText(/Tick the sets off on the day/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Set 1 done' })).toHaveCount(0)
})

test('exercise search understands gym shorthand and ignores hyphens; recent exercises come first', async ({ page }) => {
  await seed(page, { logs: [{ date: iso(-2), exerciseId: 'Hammer_Curls', sets: [{ weight: 30, reps: 10 }] }] })
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Add exercises' }).click()
  const picker = page.locator('.fixed')
  await expect(picker.locator('ul li').first()).toContainText('Hammer Curl')
  await picker.getByPlaceholder(/search/i).fill('rdl')
  await expect(picker.getByRole('button', { name: /^Romanian Deadlift/ }).first()).toBeVisible()
  await picker.getByPlaceholder(/search/i).fill('pushup')
  await expect(picker.getByRole('button', { name: /^Push-Up\b/ }).first()).toBeVisible()
  await picker.getByPlaceholder(/search/i).fill('db shoulder press')
  await expect(picker.getByRole('button', { name: /^Dumbbell Shoulder Press/ }).first()).toBeVisible()
})

test('a finished exercise folds up so the next one is in focus; any card folds or opens on demand', async ({ page }) => {
  await seed(page, { overrides: { [iso(0)]: [{ exerciseId: 'Pushups', sets: 2, reps: 10 }, { exerciseId: 'Dumbbell_Bicep_Curl', sets: 2, reps: 10 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await page.getByRole('button', { name: 'Set 1 done' }).first().click()
  await expect(page.getByRole('button', { name: 'Fold Push-Up' })).toHaveAttribute('aria-expanded', 'true') // not done yet
  await page.getByRole('button', { name: 'Set 2 done' }).first().click()
  await expect(page.getByRole('button', { name: 'Open Push-Up' })).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByText('✓ Push-Up')).toBeVisible()
  await expect(page.getByRole('spinbutton', { name: 'Set 1 reps' })).toHaveCount(1) // only the curl's sets are showing
  // Fold the curl by hand, then open both again.
  await page.getByRole('button', { name: 'Fold Dumbbell Curl' }).click()
  await expect(page.getByRole('spinbutton')).toHaveCount(0)
  await page.getByRole('button', { name: 'Open Dumbbell Curl' }).click()
  await page.getByRole('button', { name: 'Open Push-Up' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Set 1 reps' })).toHaveCount(2)
})

test('swap an exercise on the day: random from the same body part, or choose one', async ({ page }) => {
  await seed(page, { overrides: { [iso(0)]: [{ exerciseId: 'Barbell_Bench_Press_-_Medium_Grip', sets: 4, reps: 8 }, { exerciseId: 'Dumbbell_Bicep_Curl', sets: 3, reps: 12 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  const day = async () => (await state(page)).overrides[iso(0)] as { exerciseId: string; sets: number }[]

  await page.getByRole('button', { name: 'Bench Press options' }).click()
  await page.getByRole('button', { name: 'Swap exercise' }).click()
  await page.getByRole('button', { name: /^Random chest exercise/ }).click()
  let d = await day()
  expect(d[0].exerciseId).not.toBe('Barbell_Bench_Press_-_Medium_Grip')
  expect(d[0].sets).toBe(4) // same number of sets, same slot
  expect(d[1].exerciseId).toBe('Dumbbell_Bicep_Curl')

  await page.getByRole('button', { name: 'Dumbbell Curl options' }).click()
  await page.getByRole('button', { name: 'Swap exercise' }).click()
  await page.getByRole('button', { name: /^Choose one/ }).click()
  const picker = page.locator('.fixed')
  await expect(picker.getByRole('heading', { name: 'Swap Dumbbell Curl' })).toBeVisible()
  await expect(picker.getByRole('group', { name: 'Body part' }).getByRole('button', { name: 'Biceps', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await picker.getByRole('button', { name: /^Hammer Curl/ }).first().click()
  d = await day()
  expect(d[1].exerciseId).toBe('Hammer_Curls')
})

test('history from the card, and removing an exercise with logged sets asks first', async ({ page }) => {
  const BENCH = 'Barbell_Bench_Press_-_Medium_Grip'
  await seed(page, {
    overrides: { [iso(0)]: [{ exerciseId: BENCH, sets: 2, reps: 8 }] },
    logs: [{ date: iso(-5), exerciseId: BENCH, sets: [{ weight: 135, reps: 8 }, { weight: 135, reps: 7 }], note: 'shoulder ok' }],
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await page.getByRole('button', { name: 'Bench Press options' }).click()
  await page.getByRole('button', { name: 'History', exact: true }).click()
  const sheet = page.locator('.fixed')
  await expect(sheet.getByText('135×8 · 135×7')).toBeVisible()
  await expect(sheet.getByText('“shoulder ok”')).toBeVisible()
  await page.locator('.fixed').getByRole('button', { name: 'Close', exact: true }).click()

  await page.getByRole('button', { name: 'Set 1 done' }).click()
  let asked = ''
  page.removeAllListeners('dialog')
  page.on('dialog', (dlg) => { asked = dlg.message(); void dlg.accept() })
  await page.getByRole('button', { name: 'Bench Press options' }).click()
  await page.getByRole('button', { name: 'Remove exercise' }).click()
  expect(asked).toMatch(/has sets logged/)
  const s = await state(page)
  expect(s.overrides[iso(0)] ?? []).toEqual([])
  expect(s.logs.filter((l: { date: string }) => l.date === iso(0))).toEqual([]) // nothing hidden left behind
})

test('exercise picker: muscle plus equipment filters, remembered next time', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Add exercises' }).click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Chest', exact: true }).click()
  await sheet.getByRole('button', { name: /^Equipment filter/ }).click()
  await sheet.getByRole('group', { name: 'Equipment' }).getByRole('button', { name: /^Dumbbell \d+$/ }).click()
  await expect(sheet.getByRole('group', { name: 'Equipment' })).toHaveCount(0)
  const rows = sheet.locator('ul li button')
  const n = await rows.count()
  expect(n).toBeGreaterThan(5)
  for (let i = 0; i < n; i++) await expect(rows.nth(i)).toContainText('Dumbbell')
  await expect(sheet.getByText(/exercises · dumbbell · chest/)).toBeVisible()
  await sheet.getByRole('button', { name: 'Done' }).click()
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.getByText('Add an exercise').click()
  await expect(sheet.getByRole('button', { name: 'Equipment filter: Dumbbell' })).toBeVisible()
  await sheet.getByRole('button', { name: /^Equipment filter/ }).click()
  await expect(sheet.getByRole('button', { name: /^Dumbbell \d+$/ })).toHaveAttribute('aria-pressed', 'true')
})

test('equipment setting: dumbbells only shapes generated workouts and the picker', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await openSettings(page, 'Profile, units & equipment')
  await page.getByRole('radio', { name: 'Dumbbells only' }).click()
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Make me a workout' }).click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Full body', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await sheet.getByRole('button', { name: /^Add to/ }).click()
  const s = await state(page)
  const ids = (Object.values(s.overrides).flat() as { exerciseId: string }[]).map((p) => p.exerciseId)
  expect(ids.length).toBeGreaterThan(3)
  expect(ids.filter((id) => /Barbell|Cable|Machine|Smith|Leg_Press/i.test(id))).toEqual([])
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.getByText('Add an exercise').click()
  await expect(sheet.getByRole('button', { name: 'Equipment filter: my equipment' })).toBeVisible()
})

test('randomizer asks where you train: bodyweight just this once, or as the new default', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Make me a workout' }).click()
  const sheet = page.locator('.fixed')
  const gear = sheet.getByRole('radiogroup', { name: 'Equipment' })
  // One line with the usual setup; Change shows the choices.
  await expect(sheet.getByText('Full gym', { exact: true })).toBeVisible()
  await sheet.getByRole('button', { name: 'Change', exact: true }).click()
  await expect(gear.getByRole('radio', { name: 'Full gym' })).toHaveAttribute('aria-checked', 'true')
  await gear.getByRole('radio', { name: 'Bodyweight only' }).click()
  await expect(sheet.getByText('Just for this workout.')).toBeVisible()
  await sheet.getByRole('button', { name: 'Full body', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await sheet.getByRole('button', { name: /^Add to/ }).click()
  let s = await state(page)
  const ids = (Object.values(s.overrides).flat() as { exerciseId: string }[]).map((p) => p.exerciseId)
  expect(ids.length).toBeGreaterThan(3)
  expect(ids.filter((id) => /Barbell|Dumbbell|Kettlebell|Cable|Machine|Smith|Leg_Press/i.test(id))).toEqual([])
  expect(s.equipment ?? null).toBeNull() // the profile is untouched

  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.locator('.fixed').getByText('Make me a workout').click()
  await sheet.getByRole('button', { name: 'Change', exact: true }).click()
  await expect(gear.getByRole('radio', { name: 'Full gym' })).toHaveAttribute('aria-checked', 'true')
  await gear.getByRole('radio', { name: 'Dumbbells only' }).click()
  await sheet.getByRole('button', { name: 'Make it my default' }).click()
  await expect(sheet.getByText('Just for this workout.')).toBeHidden()
  s = await state(page)
  expect(s.equipment).toEqual(['Dumbbell'])
})

test('randomizer: pick cardio machines for a CrossFit WOD, or split a cardio finisher', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Make me a workout' }).click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Conditioning', exact: true }).click()
  await sheet.getByRole('button', { name: 'Hyrox / CrossFit', exact: true }).click()
  await sheet.getByRole('button', { name: 'CrossFit-style', exact: true }).click()
  const cardio = sheet.getByRole('group', { name: 'Cardio' })
  await cardio.getByRole('button', { name: 'Air bike (Assault / Echo)' }).click()
  await sheet.getByRole('button', { name: '45 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText('Air Bike (Assault / Echo)').first()).toBeVisible()
  await expect(sheet.getByText(/\d+ cal/).first()).toBeVisible()
  await sheet.getByRole('button', { name: /^Add to/ }).click()

  // A cardio finisher split across two machines, saved as the default.
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.locator('.fixed').getByText('Make me a workout').click()
  // Last time was conditioning only: tap Lifting, then add Cardio as the finisher.
  await sheet.getByRole('button', { name: 'Lifting', exact: true }).click()
  await sheet.getByRole('button', { name: 'Cardio', exact: true }).click()
  await sheet.getByRole('button', { name: 'Standard', exact: true }).click()
  await sheet.getByRole('button', { name: 'Chest', exact: true }).click()
  await cardio.getByRole('button', { name: 'Rower' }).click()
  await cardio.getByRole('button', { name: 'SkiErg' }).click()
  await sheet.getByRole('radio', { name: 'Split the time' }).click()
  await sheet.getByRole('button', { name: 'Make it my default' }).click()
  await sheet.getByRole('button', { name: '30 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText('Rower')).toBeVisible()
  await expect(sheet.getByText('SkiErg')).toBeVisible()
  const s = await state(page)
  expect(s.trainingPrefs).toMatchObject({ cardio: ['row', 'ski'], cardioSplit: true })
})

test('Make me a workout: full body is one exercise per body part, and upper or lower body is one tap', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Make me a workout' }).click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Upper body', exact: true }).click()
  for (const part of ['Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps']) await expect(sheet.getByRole('button', { name: part, exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(sheet.getByRole('button', { name: 'Quads', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await sheet.getByRole('button', { name: 'Full body', exact: true }).click()
  await sheet.getByRole('button', { name: '75 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText(/Standard · Full body · about \d+ min/)).toBeVisible()
  // Each row ends with its body part: no part twice.
  const parts = (await sheet.locator('li .text-xs').allInnerTexts()).map((t) => t.split('·').at(-1)!.trim())
  expect(parts.length).toBeGreaterThanOrEqual(8)
  expect(new Set(parts).size).toBe(parts.length)
  for (const big of ['Quads', 'Hamstrings', 'Chest', 'Back', 'Shoulders']) expect(parts).toContain(big)
})

test('exercise picker: legs and arms are split into parts, and a new exercise lands in the part you browse', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Add exercises' }).click()
  const picker = page.locator('.fixed')
  const parts = picker.getByRole('group', { name: 'Body part' })
  for (const part of ['Quads', 'Hamstrings', 'Calves', 'Biceps', 'Triceps']) await expect(parts.getByRole('button', { name: part, exact: true })).toBeVisible()
  await expect(parts.getByRole('button', { name: 'Legs', exact: true })).toHaveCount(0)
  await parts.getByRole('button', { name: 'Hamstrings', exact: true }).click()
  await expect(picker.getByRole('button', { name: /^Leg Curl/ }).first()).toBeVisible()
  await picker.getByPlaceholder(/search/i).fill('Nordic curl band')
  await picker.getByRole('button', { name: 'Bodyweight reps' }).click()
  const s = await state(page)
  expect(s.custom[0]).toMatchObject({ name: 'Nordic curl band', group: 'Hamstrings' })
})

test('cardio cards: a GPX import for runs and rides outside, not for machines', async ({ page }) => {
  await seed(page, { overrides: { [iso(0)]: [{ exerciseId: 'running', sets: 1, minutes: 20 }, { exerciseId: 'x-row-erg', sets: 1, minutes: 10 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await page.getByRole('button', { name: 'Running options' }).click()
  await expect(page.getByRole('button', { name: /Import a GPX file/ })).toBeVisible()
  await page.locator('.fixed').getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Rower options' }).click()
  await expect(page.getByRole('button', { name: /Import a GPX file/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Remove exercise' }).click()
  expect((await state(page)).overrides[iso(0)].map((p: { exerciseId: string }) => p.exerciseId)).toEqual(['running'])
})

test('warm-up sets stay with the first two weight lifts when the day is reordered, never on bodyweight', async ({ page }) => {
  await seed(page, {
    overrides: { [iso(0)]: [
      { exerciseId: 'Barbell_Squat', sets: 3, reps: 5, warmupSets: 3 },
      { exerciseId: 'Barbell_Bench_Press_-_Medium_Grip', sets: 3, reps: 5, warmupSets: 2 },
      { exerciseId: 'Pushups', sets: 3, reps: 10 },
      { exerciseId: 'Dumbbell_Bicep_Curl', sets: 3, reps: 10 },
    ] },
    logs: [{ date: iso(-2), exerciseId: 'Hammer_Curls', sets: [{ weight: 30, reps: 10 }] }],
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await page.getByRole('button', { name: '⇅ Reorder' }).click()
  for (let i = 0; i < 2; i++) await page.getByRole('button', { name: 'Move Push-Up up' }).click()
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Move Dumbbell Curl up' }).click()
  const day = (await state(page)).overrides[iso(0)] as { exerciseId: string; warmupSets?: number }[]
  expect(day.map((p) => [p.exerciseId, p.warmupSets ?? 0])).toEqual([
    ['Dumbbell_Bicep_Curl', 3], ['Pushups', 0], ['Barbell_Squat', 2], ['Barbell_Bench_Press_-_Medium_Grip', 0],
  ])
  // Progress lists the day in a few words.
  await page.locator('.fixed').getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Set 1 reps' }).first().fill('10')
  await page.locator('nav').getByText('Progress').click()
  await expect(page.getByText(/^(Arms|Chest|Legs|Full body|Upper body|Arms & legs)[^,]* · \d+ exercises?$/).first()).toBeVisible()
})

test('drop sets: add them to a planned exercise or let Make me a workout add them', async ({ page }) => {
  await seed(page, { overrides: { [iso(0)]: [{ exerciseId: 'Dumbbell_Bicep_Curl', sets: 2, reps: 10 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await page.getByRole('button', { name: 'Dumbbell Curl options' }).click()
  await page.getByRole('button', { name: 'Add a drop set' }).click()
  await page.getByRole('button', { name: 'Dumbbell Curl options' }).click()
  await page.getByRole('button', { name: 'Add another drop set' }).click()
  await expect(page.getByText(/\+2 drop/)).toBeVisible()
  await page.getByRole('spinbutton', { name: 'Set 2 lb', exact: true }).fill('40')
  await page.getByRole('button', { name: 'Set 2 done', exact: true }).click()
  // Each drop is about 20% lighter: 40 → 30 → 25 (rounded to the 5 lb dumbbell step).
  await page.getByRole('button', { name: 'Drop set 1 done' }).click()
  await page.getByRole('button', { name: 'Drop set 2 done' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Drop set 1 lb' })).toHaveValue('30')
  await expect(page.getByRole('spinbutton', { name: 'Drop set 2 lb' })).toHaveValue('25')
  let s = await state(page)
  expect(s.logs[0].sets.slice(-2).map((x: { drop?: boolean; weight: number }) => [x.drop, x.weight])).toEqual([[true, 30], [true, 25]])
  // Delete one from its set menu.
  await page.getByRole('button', { name: 'Drop set 2 options' }).click()
  await page.getByRole('button', { name: 'Delete this drop set' }).click()
  s = await state(page)
  expect(s.overrides[iso(0)][0].dropSets).toBe(1)
  expect(s.logs[0].sets.filter((x: { drop?: boolean }) => x.drop)).toHaveLength(1)

  // The randomizer can add them too.
  await page.getByRole('button', { name: '+ Add', exact: true }).click()
  await page.locator('.fixed').getByText('Make me a workout').click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Upper body', exact: true }).click()
  await sheet.getByRole('button', { name: 'Add drop sets' }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText(/\+2 drop sets/).first()).toBeVisible()
})

test('reorder a day and build supersets of any size', async ({ page }) => {
  const today = new Date().toISOString().slice(0, 10)
  const ex = ['Barbell_Bench_Press_-_Medium_Grip', 'Bent_Over_Barbell_Row', 'Dumbbell_Bicep_Curl', 'Triceps_Pushdown']
  await seed(page, { overrides: { [today]: ex.map((id) => ({ exerciseId: id, sets: 3, reps: 10 })) } })
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  const order = async () => ((await state(page)).overrides[today] as { exerciseId: string; block?: string }[])

  // Tick two in Reorder to make a superset; Split on the day undoes it.
  await page.getByRole('button', { name: '⇅ Reorder' }).click()
  for (const n of ['Bench Press', 'Barbell Row']) await page.getByRole('checkbox', { name: `Select ${n}` }).check()
  await page.getByRole('button', { name: 'Superset the 2 ticked' }).click()
  expect((await order()).slice(0, 2).map((p) => p.block)).toEqual(['ss1', 'ss1'])
  await page.locator('.fixed').getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: 'Split' }).click()
  expect((await order()).every((p) => !p.block)).toBe(true)

  // Arrows reorder.
  await page.getByRole('button', { name: '⇅ Reorder' }).click()
  await page.getByRole('button', { name: 'Move Bench Press down' }).click()
  expect((await order()).map((p) => p.exerciseId).slice(0, 2)).toEqual([ex[1], ex[0]])

  // Tick three and combine them into a giant set, then take one back out.
  for (const n of ['Barbell Row', 'Bench Press', 'Dumbbell Curl']) await page.getByRole('checkbox', { name: `Select ${n}` }).check()
  await page.getByRole('button', { name: 'Superset the 3 ticked' }).click()
  let o = await order()
  expect(o.slice(0, 3).every((p) => p.block === o[0].block && p.block)).toBe(true)
  await expect(page.getByText(/3 exercises \(giant set\)/).first()).toBeVisible()
  await page.getByRole('button', { name: 'Take Dumbbell Curl out of the superset' }).click()
  o = await order()
  expect(o.filter((p) => p.block).length).toBe(2)

  // Drag the last exercise to the top.
  const handle = page.getByRole('button', { name: 'Drag Triceps Pushdown' })
  const top = page.getByRole('button', { name: /^Drag Superset/ })
  const a = (await handle.boundingBox())!
  const b = (await top.boundingBox())!
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2)
  await page.mouse.down()
  await page.mouse.move(b.x + b.width / 2, b.y + 2, { steps: 8 })
  await page.mouse.up()
  expect((await order())[0].exerciseId).toBe(ex[3])
})

test('supersets rest once per round, not after every exercise', async ({ page }) => {
  const today = new Date().toISOString().slice(0, 10)
  const ss = { block: 'ss1', blockLabel: 'Superset' }
  await seed(page, {
    restSeconds: -1,
    overrides: { [today]: [{ exerciseId: 'Dumbbell_Bicep_Curl', sets: 2, reps: 10, ...ss }, { exerciseId: 'Triceps_Pushdown', sets: 2, reps: 10, ...ss }] },
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await expect(page.getByText(/straight into the next/)).toBeVisible()
  await expect(page.getByText(/Do one set of each, back to back, then rest/)).toBeVisible()
  const done = page.getByRole('button', { name: 'Set 1 done' })
  await done.nth(0).click()
  await expect(page.getByRole('timer')).toHaveCount(0)
  await done.nth(1).click()
  await expect(page.getByRole('timer')).toContainText('Rest')
  await page.getByRole('button', { name: 'Skip' }).click()
  // Round 2 starts with the second exercise this time: still only one rest, after both.
  await page.getByRole('button', { name: 'Set 2 done' }).nth(1).click()
  await expect(page.getByRole('timer')).toHaveCount(0)
  await page.getByRole('button', { name: 'Set 2 done' }).nth(0).click()
  await expect(page.getByRole('timer')).toContainText('Rest')
})

test('Finish workout, with a warning when sets are missing', async ({ page }) => {
  const today = new Date().toISOString().slice(0, 10)
  await seed(page, { overrides: { [today]: [{ exerciseId: 'Pushups', sets: 3, reps: 10 }, { exerciseId: 'running', sets: 1, minutes: 20 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: 'Start workout' }).click()
  await page.getByRole('spinbutton').nth(0).fill('12')
  await page.getByRole('button', { name: 'Set 1 done' }).click() // typed numbers count once the set is ticked
  await page.getByRole('button', { name: '✓ Finish workout' }).click()
  const dialog = page.getByRole('dialog', { name: 'Finish workout?' })
  await expect(dialog).toContainText('2 sets and 1 cardio session aren’t logged yet')
  await expect(dialog).toContainText('1 of 3 sets')
  await dialog.getByRole('button', { name: 'Keep going' }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: '✓ Finish workout' }).click()
  await page.getByRole('button', { name: 'Finish anyway' }).click()
  await expect(page.getByText('Workout logged ✅')).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).last().click()
  expect((await state(page)).finishedDays).toEqual([today])
  await expect(page.getByRole('button', { name: /Workout complete · see summary/ })).toBeVisible()
  // Finished by mistake? Undo it.
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  expect((await state(page)).finishedDays).toEqual([])
  await expect(page.getByRole('button', { name: '✓ Finish workout' })).toBeVisible()
  await page.getByRole('button', { name: '✓ Finish workout' }).click()
  await page.getByRole('button', { name: 'Finish anyway' }).click()
  await page.getByRole('button', { name: 'Done', exact: true }).last().click()
  await page.locator('nav').getByText('Home').click()
  await expect(page.getByText('Done for today ✓')).toBeVisible()
})

test('plan a week as a named split, with a nudge when the days do not fit it', async ({ page }) => {
  await seed(page, {})
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByRole('button', { name: /Plan a week or month/ }).click()
  await page.getByText('Next week', { exact: true }).click()
  await page.getByRole('button', { name: '4 days' }).click()
  await page.getByRole('button', { name: 'Push / Pull / Legs' }).click()
  await expect(page.getByText(/works best with 3, 5 or 6 days a week/)).toBeVisible()
  await page.getByRole('button', { name: 'Use Upper / Lower instead' }).click()
  await expect(page.getByRole('button', { name: 'Upper / Lower' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Build my plan' }).click()
  await expect(page.getByText(/Build muscle · Upper \/ Lower · 4 workouts/)).toBeVisible()
  await expect(page.getByText('Upper body', { exact: true })).toHaveCount(2)
  await expect(page.getByText('Lower body', { exact: true })).toHaveCount(2)
  await page.getByRole('button', { name: 'Apply to my plan' }).click()
  expect((await state(page)).programs[0].title).toBe('Upper / Lower week plan')
})

test('plan warm-up: pick easy cardio and set how long it lasts', async ({ page }) => {
  await seed(page, {})
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByRole('button', { name: /Plan a week or month/ }).click()
  await page.getByText('Next week', { exact: true }).click()
  await expect(page.getByText(/HIIT and timed sessions start with a short warm-up/)).toBeVisible()
  await expect(page.getByText('Warm-up length')).toBeHidden()
  await page.getByRole('button', { name: 'Easy cardio', exact: true }).click()
  await expect(page.getByText('5 min', { exact: true })).toBeVisible()
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'Longer warm-up' }).click()
  await expect(page.getByText('8 min', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Build my plan' }).click()
  await page.getByRole('button', { name: 'Apply to my plan' }).click()
  const s = await state(page)
  expect(s.genPrefs.warmMinutes).toBe(8)
  const warm = (Object.values(s.overrides).flat() as { warmup?: boolean; minutes?: number }[]).filter((p) => p.warmup && p.minutes)
  expect(warm.length).toBeGreaterThan(0)
  expect(warm.every((p) => p.minutes === 8)).toBe(true)
})

test('a lift you have never done gets a starting weight from a similar one', async ({ page }) => {
  await seed(page, {
    overrides: { [iso(0)]: [{ exerciseId: 'Dumbbell_Bench_Press', sets: 3, reps: 10 }] },
    logs: [{ date: iso(-3), exerciseId: 'Barbell_Bench_Press_-_Medium_Grip', sets: [{ weight: 185, reps: 5 }, { weight: 185, reps: 5 }] }],
  })
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await expect(page.getByText('🎯 Try 55 lb × 10')).toBeVisible()
  await expect(page.getByText(/estimated from your Bench Press \(185×5\)/)).toBeVisible()
  await page.getByRole('button', { name: 'Set 1 done' }).click()
  const s = await state(page)
  expect(s.logs.find((l: { date: string }) => l.date === iso(0)).sets[0]).toMatchObject({ weight: 55, reps: 10 })
})

test('exercise types you prefer: less machines and cables, and supersets that stay in one spot', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await openSettings(page, 'Profile, units & equipment')
  await page.getByRole('radiogroup', { name: 'Machines' }).getByRole('radio', { name: 'Less' }).click()
  await page.getByRole('radiogroup', { name: 'Cables' }).getByRole('radio', { name: 'Less' }).click()
  await page.getByRole('radiogroup', { name: 'Free weights' }).getByRole('radio', { name: 'More' }).click()
  expect((await state(page)).trainingPrefs.moves).toEqual({ machine: -1, cable: -1, free: 1 })
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Make me a workout' }).click()
  const sheet = page.locator('.fixed')
  await expect(sheet.getByText('More free weights · less machines, cables')).toBeVisible()
  await sheet.getByRole('button', { name: 'Supersets', exact: true }).click()
  await sheet.getByRole('button', { name: 'Chest', exact: true }).click()
  await sheet.getByRole('button', { name: 'Back', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await sheet.getByRole('button', { name: /^Add to/ }).click()
  const items = Object.values((await state(page)).overrides).flat() as { exerciseId: string; blockLabel?: string }[]
  expect(items.length).toBeGreaterThan(3)
  expect(items.filter((p) => /Cable|Machine|Lever|Pulldown|Smith/i.test(p.exerciseId))).toEqual([])
  expect(items.some((p) => /Superset 1 ·/.test(p.blockLabel ?? ''))).toBe(true)
})

test('Make me a workout, cardio only: running on a treadmill, intervals, is a run (not a circuit)', async ({ page }) => {
  await seed(page, { equipment: ['Barbell', 'Dumbbell', 'Kettlebell', 'Bands', 'Other'] })
  await page.goto('/')
  await page.locator('nav').getByText('Workouts').click()
  await page.getByRole('button', { name: 'Make me a workout' }).click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('group', { name: 'Kind of workout' }).getByRole('button', { name: 'Cardio' }).click()
  // Cardio on its own: no body parts, equipment or lifting styles to pick.
  await expect(sheet.getByRole('group', { name: 'Body parts' })).toHaveCount(0)
  await sheet.getByRole('group', { name: 'Cardio' }).getByRole('button', { name: 'Running' }).click()
  await sheet.getByRole('radiogroup', { name: 'Where' }).getByRole('radio', { name: 'Treadmill' }).click()
  await sheet.getByRole('radiogroup', { name: 'Kind of cardio session' }).getByRole('radio', { name: 'Intervals' }).click()
  await sheet.getByRole('button', { name: '30 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText(/Treadmill · Intervals · Indoors/)).toBeVisible()
  await expect(sheet.getByText(/Intervals · 6 min easy · 4 × 2 min hard/)).toBeVisible()
  await sheet.getByRole('button', { name: /^Add to/ }).click()
  const s = await state(page)
  const items = Object.values(s.overrides).flat() as { exerciseId: string }[]
  expect(items.map((p) => p.exerciseId)).toEqual(['Running_Treadmill'])
})

test('the app tour: a spotlight on the real screens, Back and Next only', async ({ page }) => {
  await seed(page, { tourDone: false, tourVersion: 0, overrides: { [iso(0)]: [{ exerciseId: 'Barbell_Bench_Press_-_Medium_Grip', sets: 3, reps: 8 }] } })
  await page.goto('/')
  const tour = page.getByRole('dialog', { name: 'App tour' })
  const next = tour.getByRole('button', { name: 'Next' })
  await tour.getByRole('button', { name: 'Take the tour' }).click()
  await expect(tour.getByRole('heading', { name: 'Today' })).toBeVisible()
  await expect(tour.getByText('1 of 7')).toBeVisible()
  await expect(tour.getByRole('button', { name: /Show me/ })).toHaveCount(0)
  // Everything but the tour is held still: the Start button underneath can't be pressed by accident.
  await expect(page.getByRole('button', { name: 'Start workout' }).click({ timeout: 800 })).rejects.toThrow()
  await next.click()
  await expect(tour.getByRole('heading', { name: 'Goals' })).toBeVisible()
  await tour.getByRole('button', { name: 'Back' }).click()
  await expect(tour.getByRole('heading', { name: 'Today' })).toBeVisible()
  for (const title of ['Goals', 'Settings', 'Workouts', 'Logging a set', '+ Add', 'Progress']) {
    await next.click()
    await expect(tour.getByRole('heading', { name: title })).toBeVisible()
  }
  // Stops on other tabs show those tabs.
  await expect(page.locator('nav').getByRole('button', { name: 'Workouts' })).toHaveAttribute('aria-current', 'page')
  await next.click()
  await expect(tour.getByText(/Friends are optional/)).toBeVisible()
  await tour.getByRole('button', { name: 'Let’s go' }).click()
  await expect(tour).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Today' })).toBeVisible()
  const s = await state(page)
  expect(s.tourDone).toBe(true)
  expect(s.tipsSeen).toEqual(expect.arrayContaining(['plan', 'progress']))
  expect(s.logs).toEqual([])
})
