import { expect, test } from './fixtures'
import { seed, state } from './helpers'

test('first run: name, goal and schedule build a first month, then Home shows today', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('What should we call you?').fill('Jay')
  await page.getByRole('button', { name: 'Kilograms (kg)' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: /Build muscle/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: '4', exact: true }).click()
  await page.getByRole('button', { name: 'Build my plan' }).click()
  await expect(page.getByRole('heading', { name: 'Your first week' })).toBeVisible()
  await page.getByRole('button', { name: 'Start my plan' }).click()
  await expect(page.getByRole('heading', { name: /, Jay$/ })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Today' })).toBeVisible()
  const s = await state(page)
  expect(s.programs).toHaveLength(1)
  expect(Object.keys(s.overrides).length).toBeGreaterThan(20)
  expect(s.units.weight).toBe('kg')
  expect(s.onboarded).toBe(true)
})

test('first run can be skipped straight to Home', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Skip' }).click()
  await expect(page.getByText('Nothing planned today')).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'App walkthrough' })).toHaveCount(0)
})

test('Home with nothing planned: repeat the last workout in one tap', async ({ page }) => {
  await seed(page, { logs: [{ exerciseId: 'Pushups', date: '2026-01-05', sets: [{ weight: null, reps: 15 }, { weight: null, reps: 12 }] }] })
  await page.goto('/')
  await page.getByRole('button', { name: /Repeat last workout/ }).click()
  await expect(page.getByRole('button', { name: 'Finish', exact: true })).toBeVisible()
  await expect(page.getByText('Push-Up').first()).toBeVisible()
  const s = await state(page)
  const today = Object.entries(s.overrides as Record<string, { exerciseId: string; sets: number; reps?: number }[]>).find(([, v]) => v.length)
  expect(today?.[1]).toEqual([{ exerciseId: 'Pushups', sets: 2, reps: 15 }])
  expect(s.plan.flat()).toEqual([])
})

test('Start empty, then add an exercise mid-workout', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.getByRole('button', { name: /Start empty/ }).click()
  await expect(page.getByText('Empty workout')).toBeVisible()
  await page.getByRole('button', { name: '+ Add exercise' }).click()
  await page.getByPlaceholder(/search/i).fill('bench press')
  await page.locator('.fixed button', { hasText: /^Bench Press/ }).first().click()
  await expect(page.getByText('Bench Press').first()).toBeVisible()
  expect((await state(page)).plan.flat()).toEqual([])
})

test('plan and log an exercise, then see it in History', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Add an exercise').click()
  await page.getByPlaceholder(/search/i).fill('Pushups')
  await page.locator('.fixed button', { hasText: /^Pushups/ }).first().click()
  await page.locator('.fixed').getByRole('button', { name: /Done|Close/ }).first().click()
  await page.locator('input[type=number]').first().fill('20')
  await expect.poll(async () => (await state(page)).logs.length).toBe(1)
  await page.locator('nav').getByText('History').click()
  await page.getByRole('button', { name: 'Exercises' }).click()
  await expect(page.getByText('Pushups')).toBeVisible()
})

test('randomizer builds a timed workout with a clock', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  await page.locator('.fixed').getByRole('button', { name: /More options/ }).click()
  await page.locator('.fixed').getByRole('button', { name: 'Timed', exact: true }).click()
  await page.locator('.fixed').getByRole('button', { name: 'EMOM', exact: true }).click()
  await page.locator('.fixed').getByRole('button', { name: /^Generate/ }).click()
  await page.locator('.fixed').getByRole('button', { name: /^Add to/ }).click()
  await expect(page.getByText('Timed workout').first()).toBeVisible()
  await page.getByRole('button', { name: /Start timer/ }).first().click()
  await expect(page.locator('.fixed').getByText(/Interval 1 of/)).toBeVisible()
})

test('damaged saved data does not crash the app', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('workout-app-v1', JSON.stringify({ state: { plan: 'bad', logs: [null, { exerciseId: 1 }], tourDone: true, tourVersion: 1000, socialChoice: 'declined', overrides: 5 }, version: 1 })))
  await page.goto('/')
  await expect(page.getByText('Goals')).toBeVisible()
})

test('randomizer: style groups with variations, and several styles with their own minutes', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: /More options/ }).click()
  await sheet.getByRole('button', { name: 'Strength', exact: true }).click()
  await sheet.getByRole('button', { name: 'HIIT', exact: true }).click()
  await sheet.getByRole('button', { name: 'PHA', exact: true }).click()
  await expect(sheet.getByRole('button', { name: 'HIIT circuit', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await sheet.getByRole('button', { name: 'Chest', exact: true }).click()
  await sheet.getByRole('button', { name: 'Cardio', exact: true }).click()
  await expect(sheet.getByText('Time for each part')).toBeVisible()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText(/Strength \+ PHA · Chest \+ Cardio/)).toBeVisible()
})

test('randomizer remembers the last choices, and Full body is one tap', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Full body', exact: true }).click()
  await expect(sheet.getByRole('button', { name: 'Legs', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await sheet.getByRole('button', { name: '30 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await sheet.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  await expect(sheet.getByRole('button', { name: 'Full body', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(sheet.getByRole('button', { name: '30 min', exact: true })).toHaveClass(/bg-accent/)
})

test('plan edits change one date; Repeat every weekday makes it the usual week', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: 'Add exercises' }).click()
  await page.getByPlaceholder(/search/i).fill('push-up')
  await page.locator('.fixed button', { hasText: /^Push-Up/ }).first().click()
  await page.locator('.fixed').getByRole('button', { name: /Done|Close/ }).first().click()
  let s = await state(page)
  expect(s.plan.flat()).toEqual([])
  expect(Object.values(s.overrides).flat()).toHaveLength(1)
  await expect(page.getByRole('button', { name: /Chest.*|, Chest/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Day options' }).click()
  await page.getByRole('button', { name: /^Repeat every/ }).click()
  s = await state(page)
  expect(s.plan.flat()).toHaveLength(1)
  expect(Object.keys(s.overrides)).toHaveLength(0)
  await page.getByRole('button', { name: 'Day options' }).click()
  await expect(page.getByRole('button', { name: /^Stop repeating every/ })).toBeVisible()
})

test('workout mode: steppers change weight without the keyboard', async ({ page }) => {
  await seed(page, { overrides: { [new Date().toISOString().slice(0, 10)]: [{ exerciseId: 'Barbell_Squat', sets: 2, reps: 5 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: '▶ Start workout' }).click()
  await page.getByRole('button', { name: 'More Set 1 lb' }).click()
  await page.getByRole('button', { name: 'More Set 1 lb' }).click()
  await page.getByRole('button', { name: 'More Set 1 reps' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Set 1 lb' })).toHaveValue('10')
  await expect(page.getByRole('spinbutton', { name: 'Set 1 reps' })).toHaveValue('6') // steps from the suggested 5
})
