import { expect, test } from './fixtures'
import { openSettings, seed, state } from './helpers'

test('first run: name, goal and schedule build a first month, then Home shows today', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('What should we call you?').fill('Jay')
  await page.getByRole('button', { name: 'Kilograms (kg)' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: /Build muscle/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  // Where they train, what they like, and their cardio.
  await expect(page.getByRole('heading', { name: 'Where do you usually train?' })).toBeVisible()
  await page.getByRole('radio', { name: 'CrossFit box' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: /^CrossFit-style/ }).click()
  await page.getByRole('button', { name: /^Heavy strength/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  const cardio = page.getByRole('group', { name: 'Cardio you like' })
  await expect(cardio.getByRole('button', { name: 'Stair climber' })).toBeVisible()
  await cardio.getByRole('button', { name: 'Rower' }).click()
  await cardio.getByRole('button', { name: 'Air bike (Assault / Echo)' }).click()
  await page.getByRole('radio', { name: 'Split the time between them' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: '4', exact: true }).click()
  await page.getByRole('button', { name: 'Build my plan' }).click()
  await expect(page.getByRole('heading', { name: 'Your first week' })).toBeVisible()
  await page.getByRole('button', { name: 'Start my plan' }).click()
  await expect(page.getByRole('heading', { name: /, Jay$/ })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Today' })).toBeVisible()
  const s = await state(page)
  expect(s.programs).toHaveLength(1)
  expect(Object.keys(s.overrides).length).toBeGreaterThan(20)
  expect(s.units.weight).toBe('kg')
  expect(s.onboarded).toBe(true)
  expect(s.equipment).toEqual(['Barbell', 'Dumbbell', 'Kettlebell', 'Machine', 'Other'])
  expect(s.trainingPrefs).toEqual({ styles: ['crossfit', 'strength'], cardio: ['row', 'airbike'], cardioSplit: true })
})

test('first run with no plan still asks where you train and what you like', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: /Just log my workouts/ }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('radio', { name: 'Bodyweight only' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'No preference, continue' }).click()
  // Bodyweight only: no machines to choose from, running and walking are still there.
  const cardio = page.getByRole('group', { name: 'Cardio you like' })
  await expect(cardio.getByRole('button', { name: 'Rower' })).toHaveCount(0)
  await cardio.getByRole('button', { name: 'Running' }).click()
  await page.getByRole('button', { name: 'Start using the app' }).click()
  await expect(page.getByText('Nothing planned today')).toBeVisible()
  const s = await state(page)
  expect(s.equipment).toEqual([])
  expect(s.trainingPrefs.cardio).toEqual(['run'])
  expect(s.programs ?? []).toHaveLength(0)
})

test('first run can be skipped straight to Home', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Skip' }).click()
  await expect(page.getByText('Nothing planned today')).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'App walkthrough' })).toHaveCount(0)
})

test('Home with nothing planned: repeat the last workout in one tap', async ({ page }) => {
  await seed(page, { logs: [{ exerciseId: 'Pushups', date: '2026-01-05', sets: [{ weight: null, reps: 15 }, { weight: null, reps: 12 }] }] })
  await page.goto('/')
  await page.getByRole('button', { name: /Repeat last workout/ }).click()
  await expect(page.getByRole('button', { name: 'Finish', exact: true })).toBeVisible()
  await expect(page.getByText('Push-Up').first()).toBeVisible()
  const s = await state(page)
  const today = Object.entries(s.overrides as Record<string, { exerciseId: string; sets: number; reps?: number }[]>).find(([, v]) => v.length)
  expect(today?.[1]).toEqual([{ exerciseId: 'Pushups', sets: 2, reps: 15 }])
  expect(s.plan.flat()).toEqual([])
})

test('Start empty, then add an exercise mid-workout', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.getByRole('button', { name: /Start empty/ }).click()
  await expect(page.getByText('Empty workout')).toBeVisible()
  await page.getByRole('button', { name: '+ Add exercise' }).click()
  await page.getByPlaceholder(/search/i).fill('bench press')
  await page.locator('.fixed button', { hasText: /^Bench Press/ }).first().click()
  await expect(page.getByText('Bench Press').first()).toBeVisible()
  expect((await state(page)).plan.flat()).toEqual([])
})

test('plan and log an exercise, then see it in History', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Add an exercise').click()
  await page.getByPlaceholder(/search/i).fill('Pushups')
  await page.locator('.fixed button', { hasText: /^Pushups/ }).first().click()
  await page.locator('.fixed').getByRole('button', { name: /Done|Close/ }).first().click()
  await page.locator('input[type=number]').first().fill('20')
  await expect.poll(async () => (await state(page)).logs.length).toBe(1)
  await page.locator('nav').getByText('Progress').click()
  await page.getByRole('button', { name: 'Exercises' }).click()
  await expect(page.getByText('Pushups')).toBeVisible()
})

test('randomizer builds a timed workout with a clock', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  await page.locator('.fixed').getByRole('button', { name: /More options/ }).click()
  await page.locator('.fixed').getByRole('button', { name: 'Timed', exact: true }).click()
  await page.locator('.fixed').getByRole('button', { name: 'EMOM', exact: true }).click()
  await page.locator('.fixed').getByRole('button', { name: /^Generate/ }).click()
  await page.locator('.fixed').getByRole('button', { name: /^Add to/ }).click()
  await expect(page.getByText('Timed workout').first()).toBeVisible()
  await page.getByRole('button', { name: /Start timer/ }).first().click()
  await expect(page.locator('.fixed').getByText(/Interval 1 of/)).toBeVisible()
})

test('damaged saved data does not crash the app', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('workout-app-v1', JSON.stringify({ state: { plan: 'bad', logs: [null, { exerciseId: 1 }], tourDone: true, tourVersion: 1000, socialChoice: 'declined', overrides: 5 }, version: 1 })))
  await page.goto('/')
  await expect(page.getByText('Goals')).toBeVisible()
})

test('randomizer: style groups with variations, and several styles with their own minutes', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: /More options/ }).click()
  await sheet.getByRole('button', { name: 'Strength', exact: true }).click()
  await sheet.getByRole('button', { name: 'HIIT', exact: true }).click()
  await sheet.getByRole('button', { name: 'PHA', exact: true }).click()
  await expect(sheet.getByRole('button', { name: 'HIIT circuit', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await sheet.getByRole('button', { name: 'Chest', exact: true }).click()
  await sheet.getByRole('button', { name: 'Cardio', exact: true }).click()
  await expect(sheet.getByText('Time for each part')).toBeVisible()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText(/Strength \+ PHA · Chest \+ Cardio/)).toBeVisible()
})

test('randomizer remembers the last choices, and Full body is one tap', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Full body', exact: true }).click()
  await expect(sheet.getByRole('button', { name: 'Legs', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await sheet.getByRole('button', { name: '30 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await sheet.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  await expect(sheet.getByRole('button', { name: 'Full body', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(sheet.getByRole('button', { name: '30 min', exact: true })).toHaveClass(/bg-accent/)
})

test('plan edits change one date; Repeat every weekday makes it the usual week', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: 'Add exercises' }).click()
  await page.getByPlaceholder(/search/i).fill('push-up')
  await page.locator('.fixed button', { hasText: /^Push-Up/ }).first().click()
  await page.locator('.fixed').getByRole('button', { name: /Done|Close/ }).first().click()
  let s = await state(page)
  expect(s.plan.flat()).toEqual([])
  expect(Object.values(s.overrides).flat()).toHaveLength(1)
  await expect(page.getByRole('button', { name: /Chest.*|, Chest/ }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Day options' }).click()
  await page.getByRole('button', { name: /^Repeat every/ }).click()
  s = await state(page)
  expect(s.plan.flat()).toHaveLength(1)
  expect(Object.keys(s.overrides)).toHaveLength(0)
  await page.getByRole('button', { name: 'Day options' }).click()
  await expect(page.getByRole('button', { name: /^Stop repeating every/ })).toBeVisible()
})

test('workout mode: steppers change weight without the keyboard', async ({ page }) => {
  await seed(page, { overrides: { [new Date().toISOString().slice(0, 10)]: [{ exerciseId: 'Barbell_Squat', sets: 2, reps: 5 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: '▶ Start workout' }).click()
  await page.getByRole('button', { name: 'More Set 1 lb' }).click()
  await page.getByRole('button', { name: 'More Set 1 lb' }).click()
  await page.getByRole('button', { name: 'More Set 1 reps' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Set 1 lb' })).toHaveValue('10')
  await expect(page.getByRole('spinbutton', { name: 'Set 1 reps' })).toHaveValue('6') // steps from the suggested 5
})

test('exercise picker: muscle plus equipment filters, remembered next time', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: 'Add exercises' }).click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Chest', exact: true }).click()
  await sheet.getByRole('group', { name: 'Equipment' }).getByRole('button', { name: /^Dumbbell \d+$/ }).click()
  const rows = sheet.locator('ul li button')
  const n = await rows.count()
  expect(n).toBeGreaterThan(5)
  for (let i = 0; i < n; i++) await expect(rows.nth(i)).toContainText('Dumbbell')
  await expect(sheet.getByText(/exercises · dumbbell · chest/)).toBeVisible()
  await sheet.getByRole('button', { name: 'Done' }).click()
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Add an exercise').click()
  await expect(sheet.getByRole('button', { name: /^Dumbbell \d+$/ })).toHaveAttribute('aria-pressed', 'true')
})

test('equipment setting: dumbbells only shapes generated workouts and the picker', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await openSettings(page, 'Profile, units & equipment')
  await page.getByRole('radio', { name: 'Dumbbells only' }).click()
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: 'Make a workout' }).click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: 'Full body', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await sheet.getByRole('button', { name: /^Add to/ }).click()
  const s = await state(page)
  const ids = (Object.values(s.overrides).flat() as { exerciseId: string }[]).map((p) => p.exerciseId)
  expect(ids.length).toBeGreaterThan(3)
  expect(ids.filter((id) => /Barbell|Cable|Machine|Smith|Leg_Press/i.test(id))).toEqual([])
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Add an exercise').click()
  await expect(sheet.getByRole('button', { name: /^My equipment \d+$/ })).toHaveAttribute('aria-pressed', 'true')
})

test('randomizer asks where you train: bodyweight just this once, or as the new default', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: 'Make a workout' }).click()
  const sheet = page.locator('.fixed')
  const gear = sheet.getByRole('radiogroup', { name: 'Equipment' })
  await expect(gear.getByRole('radio', { name: 'Full gym' })).toHaveAttribute('aria-checked', 'true')
  await gear.getByRole('radio', { name: 'Bodyweight only' }).click()
  await expect(sheet.getByText('Just for this workout.')).toBeVisible()
  await sheet.getByRole('button', { name: 'Full body', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await sheet.getByRole('button', { name: /^Add to/ }).click()
  let s = await state(page)
  const ids = (Object.values(s.overrides).flat() as { exerciseId: string }[]).map((p) => p.exerciseId)
  expect(ids.length).toBeGreaterThan(3)
  expect(ids.filter((id) => /Barbell|Dumbbell|Kettlebell|Cable|Machine|Smith|Leg_Press/i.test(id))).toEqual([])
  expect(s.equipment ?? null).toBeNull() // the profile is untouched

  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  await expect(gear.getByRole('radio', { name: 'Full gym' })).toHaveAttribute('aria-checked', 'true')
  await gear.getByRole('radio', { name: 'Dumbbells only' }).click()
  await sheet.getByRole('button', { name: 'Make it my default' }).click()
  await expect(sheet.getByText('Just for this workout.')).toBeHidden()
  s = await state(page)
  expect(s.equipment).toEqual(['Dumbbell'])
})

test('randomizer: pick cardio machines for a CrossFit WOD, or split a cardio finisher', async ({ page }) => {
  await seed(page)
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  await page.getByRole('button', { name: 'Make a workout' }).click()
  const sheet = page.locator('.fixed')
  await sheet.getByRole('button', { name: /More options/ }).click()
  await sheet.getByRole('button', { name: 'Hyrox / CrossFit', exact: true }).click()
  await sheet.getByRole('button', { name: 'CrossFit-style', exact: true }).click()
  const cardio = sheet.getByRole('group', { name: 'Cardio' })
  await cardio.getByRole('button', { name: 'Air bike (Assault / Echo)' }).click()
  await sheet.getByRole('button', { name: '45 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText('Air Bike (Assault / Echo)')).toBeVisible()
  await expect(sheet.getByText(/\d+ cal/).first()).toBeVisible()
  await sheet.getByRole('button', { name: /^Add to/ }).click()

  // A cardio finisher split across two machines, saved as the default.
  await page.getByRole('button', { name: '+ Add' }).click()
  await page.getByText('Randomize a workout').click()
  await sheet.getByRole('button', { name: /More options/ }).click()
  await sheet.getByRole('button', { name: 'Standard', exact: true }).click()
  await sheet.getByRole('button', { name: 'Cardio', exact: true }).click()
  await cardio.getByRole('button', { name: 'Rower' }).click()
  await cardio.getByRole('button', { name: 'SkiErg' }).click()
  await sheet.getByRole('radio', { name: 'Split the time' }).click()
  await sheet.getByRole('button', { name: 'Make it my default' }).click()
  await sheet.getByRole('button', { name: '30 min', exact: true }).click()
  await sheet.getByRole('button', { name: /^Generate/ }).click()
  await expect(sheet.getByText('Rower')).toBeVisible()
  await expect(sheet.getByText('SkiErg')).toBeVisible()
  const s = await state(page)
  expect(s.trainingPrefs).toMatchObject({ cardio: ['row', 'ski'], cardioSplit: true })
})

test('reorder a day and build supersets of any size', async ({ page }) => {
  const today = new Date().toISOString().slice(0, 10)
  const ex = ['Barbell_Bench_Press_-_Medium_Grip', 'Bent_Over_Barbell_Row', 'Dumbbell_Bicep_Curl', 'Triceps_Pushdown']
  await seed(page, { overrides: { [today]: ex.map((id) => ({ exerciseId: id, sets: 3, reps: 10 })) } })
  await page.goto('/')
  await page.locator('nav').getByText('Plan').click()
  const order = async () => ((await state(page)).overrides[today] as { exerciseId: string; block?: string }[])

  // One tap joins neighbours into a superset; Split undoes it.
  await page.getByRole('button', { name: '⤓ Superset with next' }).first().click()
  expect((await order()).slice(0, 2).map((p) => p.block)).toEqual(['ss1', 'ss1'])
  await page.getByRole('button', { name: 'Split' }).click()
  expect((await order()).every((p) => !p.block)).toBe(true)

  // Arrows reorder.
  await page.getByRole('button', { name: '⇅ Reorder' }).click()
  await page.getByRole('button', { name: 'Move Bench Press down' }).click()
  expect((await order()).map((p) => p.exerciseId).slice(0, 2)).toEqual([ex[1], ex[0]])

  // Tick three and combine them into a giant set, then take one back out.
  for (const n of ['Barbell Row', 'Bench Press', 'Dumbbell Curl']) await page.getByRole('checkbox', { name: `Select ${n}` }).check()
  await page.getByRole('button', { name: 'Superset the 3 ticked' }).click()
  let o = await order()
  expect(o.slice(0, 3).every((p) => p.block === o[0].block && p.block)).toBe(true)
  await expect(page.getByText(/3 exercises \(giant set\)/).first()).toBeVisible()
  await page.getByRole('button', { name: 'Take Dumbbell Curl out of the superset' }).click()
  o = await order()
  expect(o.filter((p) => p.block).length).toBe(2)

  // Drag the last exercise to the top.
  const handle = page.getByRole('button', { name: 'Drag Triceps Pushdown' })
  const top = page.getByRole('button', { name: /^Drag Superset/ })
  const a = (await handle.boundingBox())!
  const b = (await top.boundingBox())!
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2)
  await page.mouse.down()
  await page.mouse.move(b.x + b.width / 2, b.y + 2, { steps: 8 })
  await page.mouse.up()
  expect((await order())[0].exerciseId).toBe(ex[3])
})

test('supersets rest once per round, not after every exercise', async ({ page }) => {
  const today = new Date().toISOString().slice(0, 10)
  const ss = { block: 'ss1', blockLabel: 'Superset' }
  await seed(page, {
    restSeconds: -1,
    overrides: { [today]: [{ exerciseId: 'Dumbbell_Bicep_Curl', sets: 2, reps: 10, ...ss }, { exerciseId: 'Triceps_Pushdown', sets: 2, reps: 10, ...ss }] },
  })
  await page.goto('/')
  await page.getByRole('button', { name: '▶ Start workout' }).click()
  await expect(page.getByText(/straight into the next/)).toBeVisible()
  await expect(page.getByText(/Do one set of each, back to back, then rest/)).toBeVisible()
  const done = page.getByRole('button', { name: 'Set 1 done' })
  await done.nth(0).click()
  await expect(page.getByRole('timer')).toHaveCount(0)
  await done.nth(1).click()
  await expect(page.getByRole('timer')).toContainText('Rest')
  await page.getByRole('button', { name: 'Skip' }).click()
  // Round 2 starts with the second exercise this time: still only one rest, after both.
  await page.getByRole('button', { name: 'Set 2 done' }).nth(1).click()
  await expect(page.getByRole('timer')).toHaveCount(0)
  await page.getByRole('button', { name: 'Set 2 done' }).nth(0).click()
  await expect(page.getByRole('timer')).toContainText('Rest')
})

test('Workout complete on the Plan tab, with a warning when sets are missing', async ({ page }) => {
  const today = new Date().toISOString().slice(0, 10)
  await seed(page, { overrides: { [today]: [{ exerciseId: 'Pushups', sets: 3, reps: 10 }, { exerciseId: 'running', sets: 1, minutes: 20 }] } })
  await page.goto('/')
  await page.getByRole('button', { name: /no timer/ }).click()
  await page.getByRole('spinbutton').nth(0).fill('12')
  await page.getByRole('button', { name: '✓ Workout complete' }).click()
  const dialog = page.getByRole('dialog', { name: 'Finish workout?' })
  await expect(dialog).toContainText('2 sets and 1 cardio session aren’t logged yet')
  await expect(dialog).toContainText('1 of 3 sets')
  await dialog.getByRole('button', { name: 'Keep going' }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: '✓ Workout complete' }).click()
  await page.getByRole('button', { name: 'Finish anyway' }).click()
  await expect(page.getByText('Workout logged ✅')).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).last().click()
  expect((await state(page)).finishedDays).toEqual([today])
  await expect(page.getByRole('button', { name: /Workout complete · see summary/ })).toBeVisible()
  await page.locator('nav').getByText('Home').click()
  await expect(page.getByText('Done for today ✓')).toBeVisible()
})
